# Generated by Django 3.1.2 on 2021-11-13 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('Order_date_Time', models.DateTimeField(auto_now_add=True)),
                ('Order_Status', models.CharField(choices=[('Pending', 'Pending'), ('viewed', 'viewed'), ('Send_back', 'Send_back'), ('Approved', 'Approved')], default='Pending', max_length=10)),
                ('cost', models.FloatField()),
                ('user_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product_in',
            fields=[
                ('Product_in_id', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(default=1)),
                ('Total_cost', models.FloatField()),
                ('Product_in_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='administrator.product')),
                ('order_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='Dealer.order')),
            ],
        ),
    ]
